os: linux
dist: bionic
language: node_js
node_js:
  - "12.22.7"
  - "14.18.1"
  - "16.13.0"
  - "17.1.0"

matrix:
  include:
    - os: linux
    - os: osx
      node_js:
        - "16.13.0"
      env: 
        - CXX=g++

env:
  - CXX=g++-6
    PYTHON=3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - python3.6

before_install:
  - export JOBS=max
  - export prebuild_compile=true
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
