name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12.22.10, 14.19.0, 16.14.0, 17.4.0]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: macos deps
      if: matrix.os == 'macos-latest'
      run: brew install automake
    - name: setup msbuild
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: configure npm
      if: matrix.os == 'windows-latest'
      run: npm config set msvs_version 2019
    - name: install
      run: npm ci
    - name: test
      run: make test
